### ISSUE TITLE
这是什么垃圾项目？

### ISSUE THREAD

**Issue by ghost** [purpleroc/OpenKeeper#1]
只写了install，连uninstall都没有，上来就要最高权限，连不上网就算了，还改了其他东西导致任何网络都无法正常访问，也没法正常卸载。这种程序是拿出来坑人的么，为什么还有10个star？而且项目过期请标注或者干脆删了行吗。放在这里除了坑还有别的用？

**Comment by purpleroc** [comment]
给你带来的困扰首先表示抱歉。
其次
1. 我在项目里声明了只是修复了一个bug，整套程序并不是我写的，但放上来也的确没有考虑到小白用户对uninstall的需求，再次抱歉。
2. 不要root权限，求你告诉我怎么安装rp-pppoe？怎么进行pppoe拨号？
3. 个人认为伸手党不应该来这里，所有源码都给你了，你完全可以知道它做了什么，这个程序全是脚本，唯一一个需要编译的也只有其中生成随机头部的部分，脚本的主要作用有：
       a、编译安装rp-pppoe-3.10 
       b、拨号时在备份的pap-secrets、pppoe.conf等配置文件中新增账号密码等信息，方便拨号 
       c、拨号成功后，增加本地路由，方便访问内网。 
       按照你的描述，本程序对在你电脑上做的事情顶多就是安装了rp-pppoe（这个是用来pppoe拨号的），按照你提供的用户名密码写了pap-secrets、pppoe.conf，按道理不是造成你任何网络都访问不了的原因。
      可能造成你无法访问网络的只有修改本地路由的功能，但是，你都没拨上号，程序根本不会去修改本地路由。就算改了，你重启一下也就好了。
4. 这程序是不是坑人的也不是你说的算，有人给star，说明本程序的确帮到了他，在这里需要感谢原作者。我还看到你在其他Openkeeper相关项目下的留言，怎么说呢，这里鼓励别人使用代码，但不是无脑的使用。
5. 过没过期我并不知道，我也不知道你是怎么找到这里来的，Openkeeper主要是想突破电信使用的Netkeeper进行拨号的限制。

忘了告诉你了，这个程序可能只适用于CQUPT，其他学校我并没去过，所以也不知道。
感谢你的关注！

**Comment by ghost** [comment]
我是cqupt的，首先我不是小白，你觉得小白会大费周折用linux内核系统还知道用openKeeper连网？我只是不了解该一系列脚本到底对Ubuntu做了些什么，而且一个包里那么一堆脚本，我也懒得去看。我觉得github你放上一个项目保证它即便不能正常工作也要保证逆向可以完全解除对系统的修改。我不管理论上重启可以解决还是理论上没有修改多少系统文件，我只知道我clone编译加上完全正常的操作使用之后，无线网也不能连通。理论是一方面，但你敢在你的linux里试试么？我的环境Ubuntu16.04。解释下我为什么要发那个看起来激进的issue，你做了一个东西，就要去测试，再拿给别人用。否则项目一个个都是从别人那抓进自己的库里，用大脑运行一遍改下人脑发现的bug，看起来没问题了，又push上去，这合适吗？也许你测试了，但事实就是它对我的Ubuntu造成了严重的困扰，重启同样无法解决。显而易见，并不用谈理论。

**Comment by purpleroc** [comment]
孩子，我真的忍住了不爆粗口。
1、一个大二学弟不知道尊重珍惜各学长、前辈辛苦植树为后人好纳凉的成果，反倒觉得那是别人理所当然要做的，真为你感到悲哀。
2、我现在都觉得我还是个小白，你却认为你会用个linux而脱离了小白行列，也可见你的骄傲与自负，作为过来人，虔诚的劝你一句，虚心学习。我当时也是因为用它拨号不了了，才去认真调试，然后发现了bug，才push上来的。照你的理解，我当时是不是应该去抓住作者骂一顿呢？如此，技术会进步么？如此，问题会解决么？
3、我在校的时候的确一直用的这个，也没出现过问题，身边朋友也都是用这个，也都没问题。你说我拿你来做测试，那简直是我脑残。
4、我两年前push上去的项目，你跟我说ubuntu 16.04用不了，我该不该心里默默骂一句mdzz？（或许你又会说，过期了应该写个声明。是啊，难道你不会看提交时间？不会考虑其他问题？）
5、假若你真遇到了问题、或者麻烦，去联系信安协会那帮孩子，二教2305旁边。他们会帮你解决。
最后，再次感谢你的关注。

**Comment by Dik1s** [comment]
167***5417

MC布**迷

七班

宁夏回族自治区

同学你过来我们好好聊聊。

**Comment by Dik1s** [comment]
首先，这个程序我还在用并且没有任何问题。其次遇到问题只知道关机重启的人不知道为何有自信说自己不是小白。使用一个程序遇到问题不想去了解其问题所在而是过来找开发者喷你也是我在github见到过的第一个人。最后，请你以后不要开发程序哦，万一出了Bug用户找到你往死了喷可真是惨。最后，你也是我见过第一个CQUPT的学生在github喷人的，还是喷自己的学长。谢谢你增长了我的见识。
by the way，看到了你的学号，顺手看了一下
宁夏人
1678---417
MC---迷
那么不是小白的你，应该知道这些是什么吧，应该知道是怎么来的吧。

期待看到你push代码，我会帮助你测试的。
Good lucky to you.

**Comment by stawidy** [comment]
我有必要提醒你，openkeeper是一款开源软件，不是商业产品。开发者没有任何义务来给你提供技术支持，也没有义务去维护项目，所有的push都是志愿性质的。代码就放在那里，如果你觉得不好，你完全可以去修改，直到符合自己的需求为止。教主讲得好：Talk is cheap, show me the code!

**Comment by ghost** [comment]
回复purpleroc，我并没有因为我会用个linux就自负的不得了，你网络方向技术如此厉害还觉得自己是小白，这和我就没什么关系了，主观的东西，你很厉害，要说自己是小白，来靠自贬来绑架别人，我不评论，我只想说我不是二楼所谓遇到问题只知道重启的小白。
回复dik1s，社工一步一步来你不嫌累没关系，github我没隐藏邮箱主要是因为我觉得没人这么无聊。你无非是邮箱从Skype还是什么能得到我的名字，然后学校的查询接口也足够你查我名字学号了，至于百度账号和网易关联，学校内网漏洞百出还有很多地方都会留下帐号信息，你还通过帐号修复给我密保邮箱发钓鱼邮件？对不起，你以为我会点那两个链接吗？对了，因为一条评论，就开始做这翻箱倒柜的事情，也太没气概了吧。不如直接渗透邮件服务器，也别钓鱼了。谢谢你的厚爱，我并没有诋毁你们梓朋学长的意思。
回三楼，我听取你的意见。没什么好反驳的。不过前面两位要是说话能像你那么尊重就好了。我觉得没必要说个话每一句都尖酸刻薄的。还有，我遇到了问题就是遇到了问题，你二楼到现在还在用，跟我没什么关系。我也没喷的意思。但请你们考虑下好不容易搭建了两天的环境被三条命令毁了的感受。请二楼停止修复我的邮箱帐号？？我不会去点，谢谢。
还有，跟我说话一副站在制高点藐视的样子，也请别抱怨我的冒犯吧？

**Comment by Eventide** [comment]
几乎所有的操作都是可逆的，逆向安装脚本即可。pppoe 的话直接重新安装即可。

**Comment by Eventide** [comment]
另外欢迎使用和贡献 openkeeper-cli 。RainMark 同学和我重构了 openkeeper ，尽量减少了对系统的修改。

**Comment by purpleroc** [comment]
@ingramyang 
你若诚心问问题，想解决问题，我自然更以诚待人。
没必要你凶神恶煞跑过来，我还需笑脸相迎。
本以为还有救，后来发现，并救不了。

引用TK发过的一则典故：叫他俗子终身不识太行山。
好吧。
结贴。

**Comment by KireinaHoro** [comment]
@purpleroc 提一句，本項目似乎並沒有 LICENSE 的說。建議加上一個）

**Comment by cong-min** [comment]
😶围观

**Comment by haibincoder** [comment]
用别人的项目，还必须要求傻瓜式运行，运行不了就狂喷，过分了
