### ISSUE TITLE
关于新版本创翼是否支持

### ISSUE THREAD

**Issue by Jude-Yang** [purpleroc/OpenKeeper#3]
因为我用的时候拨号失败，所以请问现在还能正常拨号吗？如果能的话我找找是否有其他问题，谢谢。

**Comment by purpleroc** [comment]
已经离校蛮久了，并不清楚学校是否更新过。
你可以再找找看有没有其他的更新的版本吧。上次有同学给我发了新版的拨号，但没环境也没时间去调试。。。

**Comment by Jude-Yang** [comment]
感谢
